### ISSUE TITLE
[BUG] Advisor labels do not correspond PF labels (UX)

### ISSUE THREAD

**Issue by doruskova** [RedHatInsights/frontend-components#1057]
**Describe the bug**
The current styling of labels with a grey border doesn't reflect the new styling from PatternFly (https://www.patternfly.org/v4/components/label). The new filled labels should use a specific border color. These labels refer to total risk and risk of change.

**To Reproduce**
Critical total risk: (`#c9190b`)
 --pf-global--palette--red-100

Important total risk: (`#f4b678`)
--pf-global--palette--orange-100

Moderate total risk: (`#F9E0A2`)
--pf-global--palette--gold-100

Low total risk: (`#bee1f4`)
--pf-global--palette--blue-100

**Expected behavior**
Filled labels should have specific border colors, not only a grey border color.

**Screenshots**
Current state: 
<img width="992" alt="current" src="https://user-images.githubusercontent.com/32618096/113714073-4cccc780-96e8-11eb-8936-23fcc5783d38.png">

How it should look like:
<img width="150" alt="updated" src="https://user-images.githubusercontent.com/32618096/113714080-4fc7b800-96e8-11eb-94de-bb6b728ca15a.png">

**Comment by gkarat** [comment]
Hello, I would like to add my 50 cents to that bug:

The problem most probably lies in the version of the `@patternfly/react-core`: https://github.com/RedHatInsights/frontend-components/blob/master/package.json#L13.

Here is the evidence (https://codesandbox.io/s/condescending-voice-0t5jx?file=/package.json): 
![has_borders](https://user-images.githubusercontent.com/31385370/114377840-64dc9500-9b87-11eb-99ee-7cf25b4102ec.png)
![does_not_have_borders](https://user-images.githubusercontent.com/31385370/114377843-65752b80-9b87-11eb-81b7-f3f1f948dc3b.png)

So the solution should be updating the version of PF react-core you use for `frontend-components.` @Hyperkid123, could you please take a look?

**Comment by doruskova** [comment]
@gkarat Yeah! Good point. Just want to mention that this issue is related also to Insights Advisor for RHEL. Advisor for RHEL does have labels with borders but the border should be colorful, not just grey. 

In our case, it looks that we have a versioning issue.

**Comment by Hyperkid123** [comment]
> So the solution should be updating the version of PF react-core you use for frontend-components. @Hyperkid123, could you please take a look?

@gkarat you are looking at the wrong dependency list. Here is the FEC one: https://github.com/RedHatInsights/frontend-components/blob/master/packages/components/package.json#L32
Frontend components require a version greater or equal to `4.18.5` (hence the `>=`) and will not trigger any additional dependency install if the requirement is met. The version update must be done in the application. What version of FEC are you using? If it's @2.x.x do you use UMD build? IF so then you should update to @3.x.x and the problem should be fixed.

**Comment by gkarat** [comment]
@Hyperkid123, aha, thanks for pointing it out. For our application, we have the following versions of FEC:
```
    "@redhat-cloud-services/frontend-components": "2.3.11",
    "@redhat-cloud-services/frontend-components-notifications": "^2.2.4",
    "@redhat-cloud-services/frontend-components-utilities": "^2.2.8",
    "@redhat-cloud-services/rule-components": "2.2.1",
```
Could you please elaborate more on what you mean by UMD build? AFAIK we do use that build, and the problem should then lie in our FEC versions, as you said. We will try to upgrade it and tell you the result. Aleksandr Voznesenskii, our intern, should have contacted you already.

**Comment by Hyperkid123** [comment]
> Could you please elaborate more on what you mean by UMD build?

UMD build is one of many different ways to package your JS modules. The U means "universal" meaning that it will run both in browser and node environment. One HUGE disadvantage of the universality is the fact that there is no tree shaking and bundlers like webpack **will include all modules** in your build even though they are never used. For example, let's say you only use a Button from PF react-core. UDM will bundle the whole PF library. It does not care. So we have stopped shipping this version in FEC v3+

So you have two options. Migrate to v3, which does not change any API but has some import patch changes (documented in each README.md) or use direct imports to `esm/cjs` versions of the build. CJS/ESM are other build outputs that do support tree shaking. CJS is for node and ESM is for es6+ envs which is our case.

Personally, I would update to v3+ because. You don't want to stay on a legacy version for long.

> Aleksandr Voznesenskii, our intern, should have contacted you already.

Yeah, he has send an email and I gave him few tips on how to upgrade. Let me know if you will need any assistance.
