### ISSUE TITLE
### NoRegisteredSystems.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1794]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/NoRegisteredSystems/NoRegisteredSystems.tsx
 #### Ensure PF4@5 compatibility

**Comment by thatblindgeye** [comment]
I'll take this

**Comment by thatblindgeye** [comment]
Only visual difference is the spacing between the "Learn more..." button and the "Connect your systems..." text above it. This is  due to the pf4@5 branch now using the EmptyStateFooter component which provides its own `padding-top` so this should be expected.

`pf4@5`:

![NoRegisteredSystems component on pf4@5 branch](https://github.com/RedHatInsights/frontend-components/assets/70952936/210f2e79-a640-4724-b65c-33a2a15e589c)

`master`:
![NoRegisteredSystems component on master branch](https://github.com/RedHatInsights/frontend-components/assets/70952936/bc90b58f-a4db-4619-a887-99545dcc56a2)

There are also some Markup changes that are expected due to the use of the EmptyStateHeader component.

**Comment by Hyperkid123** [comment]
I am ok with the spacing changes.
