### ISSUE TITLE
### SimpleTableFilter.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1802]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/SimpleTableFilter/SimpleTableFilter.tsx
 #### Ensure PF4@5 compatibility

**Comment by thatblindgeye** [comment]
I'll take this

**Comment by thatblindgeye** [comment]
Some differences in the TextInput as well as the search icon.

`pf4@5`:
![image](https://github.com/RedHatInsights/frontend-components/assets/70952936/30960212-11cc-40e5-aa61-0d39013e18be)

The text input spans the entire width of the window and the icon sizing/placement is a bit off. The InputGroup component in PF5 expects items to be wrapped inside either InputGroupItem or InputGroupText. We have an [input group with dropdown example](https://www.patternfly.org/components/input-group#with-dropdown) that looks similar to what the intent might be here. 

Additionally we have a [text input with custom icon example](https://www.patternfly.org/components/forms/text-input#custom-icon) if the intent is to have the search icon appear "inside" of the input which may require less custom css. Worth mentioning that the TextInput component was updated in v5 and now renders with `.pf-v5-c-form-control` class applied to a wrapper `span` rather than the `input` element itself

The `className` prop is also now rendering "undefined" in the class list in the DOM since its default value was updated (previously it was an empty string).

`master`
![image](https://github.com/RedHatInsights/frontend-components/assets/70952936/29dbc07d-0c3b-4872-86d2-df7ad4720406)

Not related to any v4/v5 differences, but using our Select component rather than Dropdown might be better suited to this use-case depending on the intent of the Dropdown here. Dropdowns are typically only for triggering some action/redirecting to a link, while Select should be used for some sort of selection (and optionally triggering an action onClick).
