### ISSUE TITLE
### ErrorState.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1810]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/ErrorState/ErrorState.tsx
 #### Ensure PF4@5 compatibility

**Comment by kmcfaul** [comment]
🧷

**Comment by kmcfaul** [comment]
Icon color is now different, because custom CSS class is not targeting the correct element after v5 DOM updates (`.ins-c-error-state.pf-v5-c-empty-state .pf-v5-c-empty-state__icon` needs to be `.ins-c-error-state.pf-v5-c-empty-state .pf-v5-c-empty-state__icon svg` as the `.pf-v5-c-empty-state__icon` was raised to a wrapper instead of being applied to the svg directly).
Otherwise minor spacing differences due to new v5 classes + structure.

master:
<img width="335" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/45077788/73662874-d92b-404b-b844-32abeae7ca88">

pf4@5:
<img width="335" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/45077788/5b55f4b3-9704-45e9-9aa3-41b8e0546ac0">
