### ISSUE TITLE
### CheckboxFilter.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1836]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/ConditionalFilter/CheckboxFilter.tsx
 #### Ensure PF4@5 compatibility

**Comment by kmcfaul** [comment]
Toggle width needs `isFullWidth` on pf4@5 `MenuToggle` to match master. Otherwise only minor spacing and toggle underline differences that are expected with the switch to v5 menu components.

master:
<img width="1424" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/45077788/531927eb-6711-4439-becf-728b94cc94d4">

pf4@5:
<img width="203" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/45077788/8713ce6e-c84f-4689-8e45-9b89c0c166ad">
