### ISSUE TITLE
### NotificationPagination.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1848]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/notifications/src/NotificationPagination/NotificationPagination.tsx
 #### Ensure PF4@5 compatibility

**Comment by kmcfaul** [comment]
📃

**Comment by kmcfaul** [comment]
Master has a margin around the notification coming from a custom css class that doesn't look to be included in the pf4@5 branch. Minor spacing differences with the v5 update & change in styling on the form input control (though I'm not sure if I'm rendering something incorrectly for master because the input shouldn't look like that in v4 either).

master:
<img width="1143" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/45077788/a2dde46d-1759-4855-a6cf-6ba8831bcfc2">

pf4@5:
<img width="1143" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/45077788/165ecf1d-12be-4ada-90a7-218ff6e459db">

**Comment by Hyperkid123** [comment]
I would say that now it looks how it is supposed to look before the update.
