### ISSUE TITLE
### PrimaryToolbar.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1851]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/PrimaryToolbar/PrimaryToolbar.tsx
 #### Ensure PF4@5 compatibility

**Comment by jenny-s51** [comment]
I can take a look at this one

**Comment by jenny-s51** [comment]
A couple of discrepancies - same icon sizing issue as noted in other components. Once the icon is converted to the correct size, the spacing between the icon and text is not correct.

This can be fixed by modifying the existing class in conditional-filter.scss to:
```
  .ins-c-conditional-filter__group {
    .pf-v5-c-menu__toggle-text {
      width: auto;
      text-align: left;
        & > span {
          margin-right: var(--pf-v5-global--spacer--xs);
        }
      }
    .ins-c-conditional-filter__no-label .pf-v5-c-dropdown__toggle-text  {
      width: auto;
    }
  }
``` 

<img width="382" alt="Screenshot 2023-08-10 at 3 40 13 PM" src="https://github.com/RedHatInsights/frontend-components/assets/32821331/183b0022-7ec9-4c94-89ee-6b07897c2d26">
<img width="382" alt="Screenshot 2023-08-10 at 3 40 31 PM" src="https://github.com/RedHatInsights/frontend-components/assets/32821331/2c303e6e-2c1b-485e-a94c-7f3d2090745f">
