### ISSUE TITLE
### ConditionalFilter.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1859]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/ConditionalFilter/ConditionalFilter.tsx
 #### Ensure PF4@5 compatibility

**Comment by kmcfaul** [comment]
📁

**Comment by kmcfaul** [comment]
Text filter:
Icon sizes are different due to v5 Icon wrapping (needs to be `md` to match master).
Search icon has custom styling that is no longer applied (needs to target the svg) and icon color is now different in v5 (would need custom styling to change I think, if a core dev could confirm the color change).

master:
<img width="991" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/45077788/bd46f037-2459-4932-8eec-d2cb6594188c">

pf4@5:
<img width="991" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/45077788/29bf71e7-fc38-40d0-811b-5b7b187e08ac">

**Comment by kmcfaul** [comment]
Checkbox filter:
Needs `isFullWidth` on `MenuToggle` to match master.

master:
<img width="991" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/45077788/494698f0-4e52-4ba7-9c9a-386942e53ed0">

pf4@5:
<img width="991" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/45077788/097ff123-af6e-4d26-9981-8cafdc27f873">

**Comment by kmcfaul** [comment]
Radio filter:
Needs `isFullWidth` on `MenuToggle` to match master.

master:
<img width="991" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/45077788/bf10c490-cff7-420d-8639-988e313dac80">

pf4@5:
<img width="991" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/45077788/5eecb821-67a6-4dca-8799-e573fedacec8">
