### ISSUE TITLE
### NotAuthorized.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1871]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/NotAuthorized/NotAuthorized.tsx
 #### Ensure PF4@5 compatibility

**Comment by kmcfaul** [comment]
⛔

**Comment by kmcfaul** [comment]
Footer section requires an update to maintain visual look - wrap the return button and `actions` block in an `EmptyStateActions` component to render them on a single line, or multiple `EmptyStateActions` to render them on separate lines ([pf docs example](https://www.patternfly.org/components/empty-state#basic)). Otherwise only minor spacing differences that are expected after the v5 updates. 

master:
<img width="443" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/45077788/cdb209a9-a7f2-432b-86b9-6bf85e61c695">

pf4@5:
<img width="443" alt="image" src="https://github.com/RedHatInsights/frontend-components/assets/45077788/09925096-4e50-4b8f-b45f-0f115dcae568">
