### ISSUE TITLE
### TableToolbar.tsx

### ISSUE THREAD

**Issue by nicolethoen** [RedHatInsights/frontend-components#1875]
file: https://github.com/RedHatInsights/frontend-components/tree/master/packages/components/src/TableToolbar/TableToolbar.tsx
 #### Ensure PF4@5 compatibility

**Comment by jenny-s51** [comment]
I can take this one

**Comment by jenny-s51** [comment]
Due to the composable nature of this component, it's difficult to get an idea of how this will behave in more specific contexts. Looks like the updated v5 versions are applying the proper spacing when `ToolbarItem`s and `ToolbarGroup`s are nested within `TableToolbar.`

<img width="635" alt="Screenshot 2023-08-11 at 1 07 59 PM" src="https://github.com/RedHatInsights/frontend-components/assets/32821331/b1ee765c-7e9d-438d-aaaa-3a6530455cae">
<img width="635" alt="Screenshot 2023-08-11 at 1 08 05 PM" src="https://github.com/RedHatInsights/frontend-components/assets/32821331/defcf9b3-c937-4dba-b1c6-058efed83b5b">

**Comment by nicolethoen** [comment]
looks like those icons are a little smaller

**Comment by Hyperkid123** [comment]
I'd say we close this one. I don't think the icon size as something to block the release of the package.
