### ISSUE TITLE
PF4v4 Upgrade

### ISSUE THREAD

**Issue by Hyperkid123** [RedHatInsights/frontend-components#561]
The current progress of packages migration to PF4v4.
If anybody wants to help with migration, please add your name to the package in the list

Please use the `PF4-update` as a target branch when creating a PR. Note that tests and build for the whole monorepo will fail until all the packages are migrated. Just make sure the package you are working on build and tests pass.

- [x] utils #558 @Hyperkid123 
- [x] components #558 @Hyperkid123 
- [x] charts (does not use PF)
- [x] config (does not use PF) 
- [x] inventory #575 @karelhala  
- [ ] inventory-compliance @bastilian 
- [x] inventory-general-info #576 @karelhala 
- [x] inventory-insights https://github.com/RedHatInsights/frontend-components/pull/580 @karelhala 
- [x] notifications #562 @Hyperkid123 
- [x] pdf-generator https://github.com/RedHatInsights/frontend-components/pull/566 @Hyperkid123 
- [x] remediations  https://github.com/RedHatInsights/frontend-components/pull/567 @PanSpagetka
- [x] rule-components https://github.com/RedHatInsights/frontend-components/pull/565 @Hyperkid123 
- [x] sources #564 @rvsia 
- [x] translations (does not use PF)

Note: updated packages should be released with 2.1.0-beta version for testing purposes before stable release

**Comment by Hyperkid123** [comment]
cc @RedHatInsights/ui-reviewers

**Comment by josejulio** [comment]
Tried the `PF4-update` branch and I have one problem with the `PrimaryToolbar`, the first action button does not appear:


Before:
![Screenshot_2020-06-11_15-09-04](https://user-images.githubusercontent.com/3845764/84434484-baf24c00-abf5-11ea-986e-cbaf59e77eea.png)


After:
![Screenshot_2020-06-11_15-10-59](https://user-images.githubusercontent.com/3845764/84434504-c47bb400-abf5-11ea-9453-d618a1993d5e.png)

Looking at the html code I can see that the button is indeed there, but with `display: none`

![Screenshot_2020-06-11_15-11-51](https://user-images.githubusercontent.com/3845764/84434611-fc82f700-abf5-11ea-99fa-478920e8ac25.png)

Note that is not in the kebab
![Screenshot_2020-06-11_15-12-13](https://user-images.githubusercontent.com/3845764/84434635-09074f80-abf6-11ea-8bba-0fa7b661741c.png)

but on an iphone 6/7/8 both are there:
![Screenshot_2020-06-11_15-13-43](https://user-images.githubusercontent.com/3845764/84434746-33590d00-abf6-11ea-8c43-2144fde3c23d.png)

So i think it might be a wrong if/else in the component.

**Comment by josejulio** [comment]
I created a pull request that solves the issue: https://github.com/RedHatInsights/frontend-components/pull/568

@karelhala I see that you are working on inventory. This file also has the same issue (using `data-toolbar` instead of `toolbar` in the css)

https://github.com/RedHatInsights/frontend-components/blob/41d66f3227e582a081af5f445dbdea3f97fe5160/packages/inventory/src/InventoryList.scss#L12-L13

**Comment by bastilian** [comment]
I'm updating the `inventory-compliance` to PFv4

**Comment by carlosthe19916** [comment]
My apologies if this is not the correct place where to add an issue I'm having after upgrading to Patternfly 4 In `Migration Analytics` application:

If I use these versions:
- @patternfly/react-core: 4.22.2
- @redhat-cloud-services/frontend-components: 2.0.7 

Then  I'm not able to use the component `TableToolbar` anymore. The component `TableToolbar` is imported using:
```
import {
    TableToolbar
} from '@redhat-cloud-services/frontend-components/components/TableToolbar';
```

The error appears not when I import the component but when I try to use it. The error I see is:

```
ERROR in ./node_modules/@redhat-cloud-services/frontend-components/components/TableToolbar.js
Module not found: Error: Can't resolve '@patternfly/react-core/dist/js/layouts/Toolbar/Toolbar.js' in '/home/cferiavi/git/project-xavier/xavier-ui/node_modules/@redhat-cloud-services/frontend-components/components'
 @ ./node_modules/@redhat-cloud-services/frontend-components/components/TableToolbar.js 1:117-185
```

It seems to me that `@redhat-cloud-services/frontend-components/components/TableToolbar'` is trying to resolve `@patternfly/react-core/dist/js/layouts/Toolbar/Toolbar.js` from the wrong location. In `@patternfly/react-core` V3 the component `Toolbar.js` used to be inside the folder `layouts/Toolbar` but in the new version `@patternfly/react-core` V4 the location `layouts/Toolbar` does not exists anymore because it was moved to the folder `components/Toolbar`.

Is this something that should be fixed in `@redhat-cloud-services/frontend-components/components/TableToolbar`? or maybe there is a workaround I can use in my application?

**Comment by rvsia** [comment]
@carlosthe19916 You have to use `2.1.0-beta.6` of `@redhat-cloud-services/frontend-components`. The beta version is updated for PF4.

**Comment by karelhala** [comment]
@carlosthe19916 no worries, it's a good place to ask! If you want to upgrade to new version of PF4 you can either alias it [npm alias](https://stackoverflow.com/questions/17127054/how-do-i-install-a-package-with-npm-with-a-different-custom-module-name) or use beta version of FEC [@redhat-cloud-services/frontend-components/v/2.1.0-beta.6](https://www.npmjs.com/package/@redhat-cloud-services/frontend-components/v/2.1.0-beta.6)

**Comment by carlosthe19916** [comment]
@rvsia @karelhala just to let you know that your proposed solutions worked fine. Thank you very much!
