### ISSUE TITLE
Better error message if you are not in the VPN

### ISSUE THREAD

**Issue by josejulio** [RedHatInsights/frontend-components#966]
**Is your feature request related to a problem? Please describe.**
If for some reason you get kicked out of the VPN (or forget to connect) you will get a non-helpful message in your console: `Uncaught TypeError: Cannot read property 'classList' of null`.

**Describe the solution you'd like**
I would like a more helpful console message, maybe even explaining that you probably are not connected to the vpn.

**Comment by rvsia** [comment]
Hello,

I am not sure if something like this should be a part of frontend-components. 🤔 

However, I rewrote the proxy to [a standalone javascript utility](https://github.com/rvsia/crc-spandx) and when I run it without VPN, it shows me a bad gateway error in the browser and that proxy cannot be connected - so it's actually useful. (Probably because of a newer spandx version is used.. or due to a little bit different config.)

**Comment by josejulio** [comment]
I think there should be something telling you a better message in here: https://github.com/RedHatInsights/frontend-components/blob/master/packages/config/src/chrome-render-loader.js#L5

If no root element is found, maybe a "Couldn't find root element. It is possible that the body could't load or ..." instead of the `classList of null`. 

It wasn't easy (for me) to update and though I was doing something wrong when i saw that message.

**Comment by rvsia** [comment]
Yeah, telling that there is no root element makes sense!
